name: Deploy to Staging

on:
  push:
    branches:
      - stage

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      selenium:
        image: selenium/standalone-chrome
        ports:
          - 4444:4444

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Install Chrome
        run: |
          sudo apt-get update
          sudo apt-get install -y google-chrome-stable

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install selenium

      - name: Create SSH key file
        run: |
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > private_key
          chmod 600 private_key

      - name: Install lftp
        run: sudo apt-get install -y lftp

      - name: Create .ssh directory
        run: |
          mkdir -p ~/.ssh

      - name: Add server to known_hosts
        run: |
          ssh-keyscan -H ${{ secrets.STAGING_SERVER }} >> ~/.ssh/known_hosts

      - name: Test server connectivity with nc (netcat)
        run: |
          nc -zv ${{ secrets.STAGING_SERVER }} 22

      - name: Run Selenium tests
        run: |
          python test_selenium.py

      - name: Deploy to Staging Server via SFTP
        if: success()
        env:
          USER: ${{ secrets.STAGING_USER }}
          SERVER: ${{ secrets.STAGING_SERVER }}
          REMOTE_DIR: /home/ma506709/archysoft.com/stage/wp-content/themes/archysoft
        run: |
          lftp -e "
            set sftp:connect-program 'ssh -a -x -i private_key';
            open -u $USER,$USER sftp://$SERVER;
            mirror -R . $REMOTE_DIR;
            bye
          "

      - name: Post-Deployment Monitoring
        run: |
          sleep 30  # Подождать, пока сервисы поднимутся
          curl -X GET https://stage.archysoft.com.ua/health-check
        continue-on-error: true

      - name: Check Monitoring Status
        id: check_status
        run: echo "status=$(curl -s https://stage.archysoft.com/health-check | jq .status)" >> $GITHUB_ENV

      - name: Rollback if Monitoring Fails
        if: ${{ env.status != 'healthy' }}
        env:
          USER: ${{ secrets.STAGING_USER }}
          SERVER: ${{ secrets.STAGING_SERVER }}
          REMOTE_DIR: /home/ma506709/archysoft.com/stage/wp-content/themes/archysoft
        run: |
          lftp -e "
            set sftp:connect-program 'ssh -a -x -i private_key';
            open -u $USER,$USER sftp://$SERVER;
            mirror -R --reverse --delete . $REMOTE_DIR;
            bye
          "
